### ISSUE TITLE
IDOR Zafiyeti

### ISSUE THREAD

**Issue by regrews** [acikkaynak/doctor-chain-supply-management#46]
Merhaba,

Uygulama içerisindeki "ihtiyacım karşılandı" fonksiyonu tetiklendiğinde "/api/account/recipes/change-status" URL adresine gönderilen POST isteği içerisinde bulunan "Id" parametresine girilen değere göre ilgili talep direkt olarak "ihtiyaç karşılandı" şeklinde kayıt edilmektedir. Bu noktada Id parametresinin aldığı değerin ilgili kullanıcı tarafından açılıp açılmadığının kontrolünün yapılması önerilmektedir.

![image](https://user-images.githubusercontent.com/24255951/220187920-a6490f9f-2ecd-4598-9f68-8cfe8af9fe51.png)

**Comment by sustartx** [comment]
Sorun giderildi, teşekkürler.
